### ISSUE TITLE
Mandar obxecto do evento ás funcións rexistradas

### ISSUE THREAD

**Issue by bertez** [MiniPlugins/delegato#3]

**Comment by oscarotero** [comment]
Eu mandaríaas como primeiro argumento sempre: 

``` js
args.unshift(e)
```

**Comment by bertez** [comment]
Si, esa era a miña idea, pero en calquera caso se se inicializa con includeJquery sería mellor non mandar ese obxecto. Correcto?

**Comment by oscarotero** [comment]
:+1:
